### ISSUE TITLE
Error in UserDefinition with Humhub 1.14.0-beta.1 and Rest API module 0.8.0

### ISSUE THREAD

**Issue by funkycram** [humhub/rest#108]
If I do:
```
curl -H 'Content-Type: application/json' -H 'Authorization: Bearer xxxxxxxxxxxx' https:/my-humhub.com/api/v1/post
```

I get:
```
TypeError: humhub\modules\rest\definitions\UserDefinitions::getUserShort(): Argument #1 ($user) must be of type humhub\modules\user\models\User, null given, called in /var/www/hhdev/protected/modulesnoncuzy/rest/definitions/ContentDefinitions.php on line 50 and defined in /var/www/hhdev/protected/modulesnoncuzy/rest/definitions/UserDefinitions.php:22
Stack trace:
#0 /var/www/hhdev/protected/modulesnoncuzy/rest/definitions/ContentDefinitions.php(50): humhub\modules\rest\definitions\UserDefinitions::getUserShort()
#1 /var/www/hhdev/protected/modulesnoncuzy/rest/definitions/ContentDefinitions.php(28): humhub\modules\rest\definitions\ContentDefinitions::getContentMetadata()
#2 /var/www/hhdev/protected/modulesnoncuzy/rest/definitions/PostDefinitions.php(24): humhub\modules\rest\definitions\ContentDefinitions::getContent()
#3 /var/www/hhdev/protected/modulesnoncuzy/rest/controllers/post/PostController.php(33): humhub\modules\rest\definitions\PostDefinitions::getPost()
#4 /var/www/hhdev/protected/modulesnoncuzy/rest/components/BaseContentController.php(82): humhub\modules\rest\controllers\post\PostController->returnContentDefinition()
#5 [internal function]: humhub\modules\rest\components\BaseContentController->actionFind()
#6 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#7 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#8 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#9 /var/www/hhdev/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#10 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#11 /var/www/hhdev/index.php(26): yii\base\Application->run()
#12 {main}
```

It was working with Humhub 1.13 and Rest API 0.7
Thanks.

**Comment by funkycram** [comment]
Thanks @gevorgmansuryan that fixed the bug!
